services:
  - type: web
    name: amigao
    env: node
    plan: free
    buildCommand: bash build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORCE_REBUILD
        value: "true"
